### ISSUE TITLE
CocoaPods could not find compatible versions for pod "RCTACPTarget"

### ISSUE THREAD

**Issue by ims7inc** [adobe/react-native-acptarget#15]
[!] CocoaPods could not find compatible versions for pod "RCTACPTarget":
  In Podfile:
    RCTACPTarget (from `../node_modules/@adobe/react-native-acptarget`)

Specs satisfying the `RCTACPTarget (from `../node_modules/@adobe/react-native-acptarget`)` dependency were found, but they required a higher minimum deployment target.

#### Steps to Reproduce
trying to do `pod install`

#### Platform and Version
platform :ios, '9.0'

**Comment by nporter-adbe** [comment]
Hi @ims7inc sorry for the delay. The Adobe AEP SDK has a minimum iOS version of 10.0. You'll need to increase the deployment target for your app to at least 10.0+, and also update your podfile to be 10.0+.
