### ISSUE TITLE
ACPTargetRequestObject doesn't work in Android 9,10

### ISSUE THREAD

**Issue by lutakyn** [adobe/react-native-acptarget#28]
### Expected Behaviour
I must get response from ACPTargetRequestObject function with mbox parameter in Android 9 and and Android 10

### Actual Behaviour
I don't get any response, its undefined.

#### Steps to Reproduce
Run code on phone with Android 9 or Android 10

#### Platform and Version
 buildToolsVersion = "28.0.3"
        minSdkVersion = 19
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"

 OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
    Memory: 132.30 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.13.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29
      Build Tools: 26.0.2, 27.0.3, 28.0.3, 29.0.0, 29.0.1
      System Images: android-19 | Intel x86 Atom, android-21 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: ^0.61.1 => 0.61.1 
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-git-upgrade: 0.2.7

#### Sample Code that illustrates the problem
```
var request1 = new ACPTargetRequestObject("mboxName2", parameters1, "defaultContent1", (error, content) => {
  if (error) {
    console.error(error);
  } else {
    console.log("Adobe content:" + content);
  }
});

var parameters2 = new ACPTargetParameters(mboxParameters1, {"profileParameters": "parameterValue"}, targetProduct, targetOrder);
var request2 = new ACPTargetRequestObject("mboxName2", parameters2, "defaultContent2", (error, content) => {
  if (error) {
    console.error(error);
  } else {
    console.log("Adobe content:" + content);
  }
});
var locationRequests = [request1, request2];
```

**Comment by andresesfm** [comment]
Did you miss including the second part: 
```
var profileParameters1 = {"ageGroup": "20-32"};

var parameters = new ACPTargetParameters({"parameters": "parametervalue"}, profileParameters1, targetProduct, targetOrder);
ACPTarget.retrieveLocationContent(locationRequests, parameters);
``` ?
